# Generated by Django 2.1.15 on 2021-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supperuser',
            field=models.BooleanField(default=False),
        ),
    ]
